### ISSUE TITLE
Shouldn't we get a new Release from Master

### ISSUE THREAD

**Issue by RainerBielefeld** [funktechno/kanboard-plugin-wiki#64]
This issue is:

- [X] Discussion

More tests required or what is the obstacle?

CU

Rainer

**Comment by RainerBielefeld** [comment]
We really need some progress here!

**Comment by twiguard** [comment]
Seriously, the version 0.3.2 hasn't been working with the latest Kanboard versions for at least half a year.

**Comment by imfx77** [comment]
It's been about 10 months since I keep [a fork of the Wiki repo](https://github.com/imfx77/kanboard-plugin-Wiki) with 2 fixes that allow me to use the plugin with the latest KB version.
Both are simple and straightforward enough to be merged and committed to the Master, yet are not. And at some point I just stopped wandering why and made the fork for myself. Feel free to get the patches from there if you need.

**Comment by alfredbuehler** [comment]
Sad to say that this plugin is dead.

**Comment by RainerBielefeld** [comment]
Patches somewhere in the far corner of the coal cellar are of no use to anyone. We should do a fork with your patched version and integrate that patched Wiki Plugin fork into the KANBOARD Plugins List.

**Comment by creecros** [comment]
https://github.com/funktechno/kanboard-plugin-wiki/pull/58#issuecomment-2236353745

Things will happen.

**Comment by lastlink** [comment]
new version release pending https://github.com/kanboard/website/pull/510
